# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: devmatias
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: my-app-express
# "service" is the name of this project. This will also be added to your AWS resource names.
service: my-app-express

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: handler.handler
    test: handler.test
    events:
      - httpApi: "*"
